Expiring email
staynomad/Nomad-Back pull request #152
Opened 2021-07-10 05:07 UTC by syd-tan

# Send host an email when listing is about to expire

Closes #70 

# Summary of change

1. Created reminderMail.js (/routes) which should:
- go through all the listings every day at 8:00 am PST 
- check whether a reminder has been sent already and if the listing is set to expire within a week
- send a reminder to the corresponding host 
- mark the listing reminder as sent, so the host should only receive one reminder per expiring listing
- repeat process for each listing

# Testing/Verification

- checked to make sure email reminder could be sent
- made sure function properly filters listings that expire within a week
- made sure node cron runs task at the right interval (tested by sending emails every minute)

Still need to make sure that emails are not sent repeatedly for each listing and that emails are sent to the correct host.

2021-07-10 20:00 UTC, aidenszeto requested changes
Looks good for the most part, here's a few nits:
 - The cron job (lines 16-21 of `reminderMail.js`) can be moved to `app.js` so that it's with our other jobs
 - The mongoose connection code can be removed since the cron job will be run through the server, which already creates the connection with our database
 - Since the `findExpiredListings()` function isn't a route (not an endpoint in our API), we can move it to a file in /helpers
   
The overall architecture would have `findExpiredListings()` in the `reminder.helper.js` file and the cron job in `app.js` so we likely won't need anything in /routes.

2021-07-10 20:09 UTC, aidenszeto requested changes
Added a few comments, feel free to ping on Slack for clarifications on any of them!

2021-07-10 20:09 UTC, aidenszeto commented on routes/reminderMail.js
> +    for await (const listing of Listing.find({})) {
It might be worth it set `Listing.find({})` to a const here, then iterate through to cut down on loop overhead

2021-07-10 20:09 UTC, aidenszeto commented on routes/reminderMail.js
> +        let listDate = new Date(listing.available[1]);
Doesn't look like `listDate` gets changed so we could keep it as a const here

2021-07-10 20:09 UTC, aidenszeto commented on routes/reminderMail.js
> +          let email = user.email;
Same here on lines 43 and 44, could we change these to const?

2021-07-11 02:21 UTC, aidenszeto approved these changes

2021-07-12 02:23 UTC, teekenzie approved these changes

2021-07-13 04:00 UTC, merged